# Generated by Django 2.2.12 on 2025-05-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userintegration",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userintegration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("completed", "COMPLETED"),
                    ("failed", "FAILED"),
                ],
                db_index=True,
                default="pending",
                max_length=255,
            ),
        ),
    ]
