# Generated by Django 3.2.25 on 2025-05-17 05:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_auto_20250515_1847"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userintegration",
            options={"get_latest_by": "modified"},
        ),
        migrations.AddField(
            model_name="userintegration",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="userintegration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userintegration",
            name="integration_name",
            field=models.CharField(
                choices=[("fitbit", "FITBIT"), ("strava", "STRAVA")],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
