# Generated by Django 3.2.25 on 2025-05-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_auto_20250517_0530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userintegration",
            name="access_token",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="userintegration",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
