name: Deploy runsync to GCE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.GCE_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to GCE
      run: |
        ssh ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} << 'EOF'
          if [ -d "runsync" ]; then
            cd runsync
            git pull origin master
          else
            git clone https://github.com/${{ github.repository }}.git runsync
            cd runsync
          fi
          # Build Docker image
          docker build -t runsync .
          # Stop and remove any existing container
          docker stop runsync || true
          docker rm runsync || true
          # Run the new container
          docker run -d --name runsync --env-file .env -p 8000:8000 runsync
        EOF
