name: Deploy runsync to GCE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.GCE_HOST }} >> ~/.ssh/known_hosts

      - name: Upload .env
        run: |
          echo "${{ secrets.ENV_FILE }}" | ssh ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} "cat > ~/runsync/.env"

      - name: Deploy to GCE
        run: |
          ssh ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} << 'EOF'

          # Add GitHub to known_hosts to avoid host verification errors
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

          # Check if runsync directory exists, create if not
          if [ ! -d "runsync" ]; then
            git clone https://github.com/shubhamgrg04/runsync.git runsync
          else
            cd runsync
            git pull origin master
          fi


          # Ensure .env is present (copy from a safe location or create it here)
          if [ ! -f .env ]; then
            echo "Missing .env file! Please upload it to the server."
            exit 1
            fi

          # Check if Docker is installed, install if not
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl gnupg lsb-release
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
              $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            sudo systemctl start docker || sudo service docker start
            sudo systemctl enable docker || sudo service docker enable
          fi

          # Build Docker image (ensure you are in the correct directory)
          sudo docker build -t runsync .

          # Stop and remove any existing container
          sudo docker stop runsync || true
          sudo docker rm runsync || true

          # Run the new container
          sudo docker run -d --name runsync --env-file .env -p 8000:8000 runsync
